package com.example.ui.theme

import com.example.ui.viewmodel.AppLanguage

object HarvestHubStrings {

    fun get(key: String, language: AppLanguage): String {
        return when (language) {
            AppLanguage.HINDI -> hindiMap[key] ?: englishMap[key] ?: key
            AppLanguage.TELUGU -> teluguMap[key] ?: englishMap[key] ?: key
            AppLanguage.ENGLISH -> englishMap[key] ?: key
        }
    }

    private val englishMap = mapOf(
        "app_title" to "HarvestHub",
        "app_subtitle" to "Paddy Procurement & Queue System",
        "tab_queue" to "Live Queue",
        "tab_book" to "Book Slot",
        "tab_assay" to "Quality & Weight",
        "tab_dbt" to "DBT & SMS",
        "greeting" to "Namaste,",
        "registered_farmer" to "Verified Farmer",
        "active_token" to "Active Token",
        "arrival_recommendation" to "Optimal Arrival Time",
        "leave_by" to "Leave village by",
        "tokens_ahead" to "Vehicles Ahead in Queue",
        "est_wait" to "Estimated Wait Time",
        "assigned_gate" to "Assigned Entry Gate",
        "advance_stage" to "Simulate Next Stage",
        "simulate_queue" to "Simulate Queue Move",
        "no_active_booking" to "No active delivery slot. Book your slot now to avoid waiting.",
        "book_new_slot" to "Book New Slot",
        "mandi_status" to "Mandi Handling Status",
        "daily_quota" to "Daily Quota Remaining",
        "digital_weighment_slip" to "Digital Weighment Slip",
        "moisture_testing" to "Digital Moisture & Assaying",
        "moisture_content" to "Grain Moisture Content",
        "quality_grade" to "Approved Quality Grade",
        "official_msp" to "Official MSP Rate",
        "net_paddy_weight" to "Net Paddy Weight",
        "gross_weight" to "Gross Weight",
        "tare_weight" to "Tare (Empty Vehicle)",
        "total_amount" to "Total Amount Payable",
        "dbt_tracker" to "Direct Benefit Transfer (DBT) Tracker",
        "aadhaar_linked" to "Aadhaar-Linked Bank Account",
        "recent_sms" to "Live SMS Updates Received",
        "step_booked" to "Slot Booked",
        "step_arrived" to "Gate Entry",
        "step_tested" to "Quality Approved",
        "step_weighed" to "Weighed on Scale",
        "step_paid" to "DBT Disbursed",
        "select_center" to "Select Procurement Center (PPC/Mandi)",
        "crop_variety" to "Crop Variety",
        "est_yield" to "Estimated Quantity (Quintals)",
        "vehicle_type" to "Transport Vehicle",
        "vehicle_num" to "Vehicle Registration Number",
        "slot_date" to "Delivery Date",
        "slot_time" to "Preferred Time Slot",
        "confirm_slot" to "Generate Digital Token & Book Slot",
        "why_slots" to "Why Book in Advance?",
        "slot_benefit_1" to "Guaranteed entry gate clearance without road congestion",
        "slot_benefit_2" to "Saves ₹800 - ₹1,500 in daily tractor rental and idling diesel costs",
        "slot_benefit_3" to "Eliminates crop exposure to overnight rain and mold"
    )

    private val hindiMap = mapOf(
        "app_title" to "हार्वेस्टहब",
        "app_subtitle" to "धान खरीद और कतार प्रबंधन",
        "tab_queue" to "लाइव कतार",
        "tab_book" to "स्लॉट बुकिंग",
        "tab_assay" to "गुणवत्ता व वजन",
        "tab_dbt" to "डीबीटी व एसएमएस",
        "greeting" to "नमस्ते,",
        "registered_farmer" to "पंजीकृत किसान",
        "active_token" to "सक्रिय टोकन",
        "arrival_recommendation" to "उचित पहुंचने का समय",
        "leave_by" to "गाँव से रवाना हों",
        "tokens_ahead" to "कतार में आगे वाहन",
        "est_wait" to "अनुमानित प्रतीक्षा समय",
        "assigned_gate" to "आवंटित प्रवेश द्वार",
        "advance_stage" to "अगला चरण सिमुलेट करें",
        "simulate_queue" to "कतार आगे बढ़ाएं",
        "no_active_booking" to "कोई सक्रिय स्लॉट नहीं है। मंडी में बिना लाइन के बेचने हेतु स्लॉट बुक करें।",
        "book_new_slot" to "नया स्लॉट बुक करें",
        "mandi_status" to "मंडी प्रसंस्करण स्थिति",
        "daily_quota" to "दैनिक क्षमता शेष",
        "digital_weighment_slip" to "डिजिटल तौल रसीद",
        "moisture_testing" to "डिजिटल नमी व ग्रेड जांच",
        "moisture_content" to "धान में नमी की मात्रा",
        "quality_grade" to "स्वीकृत गुणवत्ता ग्रेड",
        "official_msp" to "सरकारी एमएसपी दर",
        "net_paddy_weight" to "शुद्ध धान वजन",
        "gross_weight" to "सकल वजन (वाहन सहित)",
        "tare_weight" to "खाली वाहन वजन (टार)",
        "total_amount" to "कुल देय राशि",
        "dbt_tracker" to "डीबीटी बैंक खाता ट्रैकर",
        "aadhaar_linked" to "आधार लिंक बैंक खाता",
        "recent_sms" to "प्राप्त लाइव एसएमएस अलर्ट",
        "step_booked" to "स्लॉट बुक हुआ",
        "step_arrived" to "गेट प्रवेश",
        "step_tested" to "गुणवत्ता पास",
        "step_weighed" to "कांटा तौल पूर्ण",
        "step_paid" to "डीबीटी भुगतान सफल",
        "select_center" to "धान खरीद केंद्र चुनें",
        "crop_variety" to "धान की किस्म",
        "est_yield" to "अनुमानित मात्रा (क्विंटल)",
        "vehicle_type" to "परिवहन वाहन",
        "vehicle_num" to "वाहन नंबर",
        "slot_date" to "पहुंचने की तारीख",
        "slot_time" to "पसंदीदा समय स्लॉट",
        "confirm_slot" to "डिजिटल टोकन जनरेट व बुक करें",
        "why_slots" to "स्लॉट बुकिंग क्यों जरूरी है?",
        "slot_benefit_1" to "गेट पर बिना जाम तुरंत प्रवेश की गारंटी",
        "slot_benefit_2" to "ट्रैक्टर किराए व डीजल में रोजाना ₹800-₹1500 की बचत",
        "slot_benefit_3" to "रात में खुले में बारिश और फसल खराब होने से बचाव"
    )

    private val teluguMap = mapOf(
        "app_title" to "హార్వెస్ట్‌హబ్",
        "app_subtitle" to "వరి సేకరణ మరియు క్యూ నిర్వహణ",
        "tab_queue" to "లైవ్ క్యూ",
        "tab_book" to "స్లాట్ బుకింగ్",
        "tab_assay" to "నాణ్యత & తూకం",
        "tab_dbt" to "DBT & SMS",
        "greeting" to "నమస్కారం,",
        "registered_farmer" to "ధృవీకరించబడిన రైతు",
        "active_token" to "యాక్టివ్ టోకెన్",
        "arrival_recommendation" to "సరైన రాక సమయం",
        "leave_by" to "గ్రామం నుండి బయలుదేరండి",
        "tokens_ahead" to "ముందున్న వాహనాలు",
        "est_wait" to "అంచనా వేచి ఉండే సమయం",
        "assigned_gate" to "కేటాయించిన గేట్",
        "advance_stage" to "తదుపరి దశను చూడండి",
        "simulate_queue" to "క్యూ కదలిక సిమ్యులేషన్",
        "no_active_booking" to "యాక్టివ్ డెలివరీ స్లాట్ లేదు. సమయం ఆదా చేయడానికి స్లాట్ బుక్ చేయండి.",
        "book_new_slot" to "కొత్త స్లాట్ బుక్ చేయండి",
        "mandi_status" to "మార్కెట్ సామర్థ్యం",
        "daily_quota" to "రోజువారీ కోటా మిగిలింది",
        "digital_weighment_slip" to "డిజిటల్ తూకం రశీదు",
        "moisture_testing" to "డిజిటల్ తేమ & నాణ్యత పరీక్ష",
        "moisture_content" to "ధాన్యంలో తేమ శాతం",
        "quality_grade" to "ఆమోదించబడిన నాణ్యత గ్రేడ్",
        "official_msp" to "ప్రభుత్వ MSP ధర",
        "net_paddy_weight" to "నికర వరి బరువు",
        "gross_weight" to "మొత్తం బరువు (వాహనంతో)",
        "tare_weight" to "ఖాళీ వాహనం బరువు",
        "total_amount" to "చెల్లించవలసిన మొత్తం",
        "dbt_tracker" to "DBT బ్యాంక్ ఖాతా ట్రాకర్",
        "aadhaar_linked" to "ఆధార్-లింక్డ్ బ్యాంక్ ఖాతా",
        "recent_sms" to "వచ్చిన లైవ్ SMS అలర్టులు",
        "step_booked" to "స్లాట్ బుక్ అయింది",
        "step_arrived" to "గేట్ ప్రవేశం",
        "step_tested" to "నాణ్యత ఆమోదం",
        "step_weighed" to "తూకం పూర్తయింది",
        "step_paid" to "డబ్బు జమ అయింది",
        "select_center" to "సేకరణ కేంద్రాన్ని ఎంచుకోండి",
        "crop_variety" to "వరి రకం",
        "est_yield" to "అంచనా దిగుబడి (క్వింటాళ్ళు)",
        "vehicle_type" to "వాహనం రకం",
        "vehicle_num" to "వాహనం నంబరు",
        "slot_date" to "డెలివరీ తేదీ",
        "slot_time" to "సమయం స్లాట్",
        "confirm_slot" to "డిజిటల్ టోకెన్ బుక్ చేయండి",
        "why_slots" to "ముందుగా స్లాట్ బుక్ చేసుకోవడం ఎందుకు?",
        "slot_benefit_1" to "గేట్ వద్ద వేచి ఉండకుండా వేగవంతమైన ప్రవేశం",
        "slot_benefit_2" to "ట్రాక్టర్ అద్దె మరియు డీజిల్ ఖర్చులలో ₹800-₹1500 వరకు ఆదా",
        "slot_benefit_3" to "వర్షం మరియు ధాన్యం నష్టం నుండి రక్షణ"
    )
}
